"""Auto migration 9d0e9ba3-b500-448e-912a-df8754a9d392

Revision ID: 0865451fec29
Revises: 
Create Date: 2025-05-02 02:32:50.206888

"""
from typing import Sequence, Union
import jarvis_integration
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0865451fec29'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image_url', sa.String(), nullable=True))
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'user_voice',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('user', 'settings',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'last_active_at')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'user_face')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.BIGINT(), nullable=True))
    op.add_column('user', sa.Column('user_face', sa.TEXT(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.BIGINT(), nullable=True))
    op.add_column('user', sa.Column('last_active_at', sa.BIGINT(), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'settings',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user', 'user_voice',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'profile_image_url')
    # ### end Alembic commands ###
