"""Database of Jarvis

Revision ID: 9f13e4ea1566
Revises: 
Create Date: 2025-01-27 20:47:51.328271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import utils

# revision identifiers, used by Alembic.
revision: str = '9f13e4ea1566'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file', utils.internals.db.JSONField(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('settings', utils.internals.db.JSONField(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tools',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('func', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('settings', utils.internals.db.JSONField(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=False),
    sa.Column('call_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('duration', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('twilio_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_sid', sa.String(), nullable=False),
    sa.Column('auth_token', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('dob', sa.String(), nullable=True),
    sa.Column('user_face', sa.Text(), nullable=True),
    sa.Column('user_voice', sa.Text(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('last_active_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('settings', utils.internals.db.JSONField(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone_numbers')
    op.drop_table('user')
    op.drop_table('twilio_settings')
    op.drop_table('contacts')
    op.drop_table('call_history')
    op.drop_table('Tools')
    op.drop_table('Agents')
    # ### end Alembic commands ###
